version: '3.8'

services:
  samba:
    container_name: docker_smb
    tty: true
    # Name of your pc
    hostname: docker_smb
    network_mode: host
    build:
      context: .
      shm_size: '100mb'
      dockerfile: Dockerfile
    volumes:
      - /media/hd/ps2:/media/ps2:rw
