version: '3.8'

services:
  samba:
    container_name: docker_smb
    tty: true
    # Name of your pc
    hostname: server
    network_mode: host
    build:
      context: .
      shm_size: '100mb'
      dockerfile: Dockerfile
    volumes:
      - /storage/media/games/PS2/ps2smb:/media/ps2:rw
