version: '3.8'

services:
  samba:
    container_name: docker_smb
    tty: true
    # Name of your pc
    hostname: HP
    network_mode: host
    build:
      context: .
      shm_size: '100mb'
      dockerfile: Dockerfile
    volumes:
      - /home/luiz/SMB/:/media/SMB:rw
      - /home/luiz/:/media/HOME:rw
      - /media/luiz/HD:/media/HD:rw
      - /home/luiz/RetroPie/roms:/media/roms:rw
      - /home/luiz/RetroPie/BIOS:/media/BIOS:rw
      - /opt/retropie/configs:/media/configs:rw
      - /home/luiz/RetroPie/splashscreens:/media/splashscreens:rw
